#!perl
use strict;
use 5.008001;
use warnings;
use App::revealup::cli;

App::revealup::cli->new->run(@ARGV);

__END__

=head1 NAME

revealup - Web app for showing Markdown as slides

=head1 SYNOPSIS

revealup serve -p 5000

 Options:
   -p        HTTP Port Number
   --theme   CSS filename or path

=cut
